### ISSUE TITLE
"TypeError: AWSXRay.captureAWSv3Client is not a function"

### ISSUE THREAD

**Issue by nickitza** [aws/aws-xray-sdk-node#396]
Been struggling getting AWSXray to work with my s3 client, and keep getting the "TypeError: AWSXRay.captureAWSv3Client is not a function" on the import. This is how I've imported:

const AWSXRay = require('aws-xray-sdk')
const { S3, GetObjectCommand, CopyObjectCommand } = require('@aws-sdk/client-s3')
const s3 = AWSXRay.captureAWSv3Client(new S3({}))

I have version 3.2.0 in package.json. The v3 client modules work on their own, but as soon as I try to capture it, it errors. Any help would be greatly appreciated. Thank you!

**Comment by willarmiros** [comment]
Hi @nickitza,

The changes to capture V3 clients are not yet released, so they won't be available in 3.2.0 which is why you received that error. They'll be included in the next 3.3.0 release, which should be coming soon. Stay tuned!

**Comment by BorntraegerMarc** [comment]
Using v3.3.4 I still get the same error @willarmiros

**Comment by BorntraegerMarc** [comment]
Oh, I see it's because of this release roll-back: https://github.com/aws/aws-xray-sdk-node/releases/tag/aws-xray-sdk-node%403.3.1
